### ISSUE TITLE
New trigger type: ConditionalPeriodicTrigger

### ISSUE THREAD

**Issue by MadsVSChristensen** [cph-cachet/carp.sensing-flutter#230]
Suggestion of creating a new trigger ConditionalPeriodicTrigger which check if the Task should be triggered on a periodic timer and NOT on a sampling event as ConditionalSamplingEventTrigger.

**Comment by bardram** [comment]
I've implemented this trigger and released as version `0.31.2`. 

Note, however, that the `ConditionalEvaluator` function looks like this

```
typedef ConditionalEvaluator = bool Function();
```

Hence, there are no `DataPoint` (as in the `ConditionalEventEvaluator` function), since the ConditionalPeriodicTrigger on trigger based on a `period` (and not a data point event).

I hope it is useful.
