### ISSUE TITLE
[carp_esense_package] Status is not updated when sampling data

### ISSUE THREAD

**Issue by luciamontesinos** [cph-cachet/carp.sensing-flutter#254]
`deviceStatus` is not being updated when  `eSenseStream `is listening for events. I'm not sure if the status should be updated always (including when it's a `BatteryRead` event) or only when there is the proper data sampling (`ESENSE_BUTTON` and `ESENSE_BUTTON`)

Therefore, missing adding  `status = DeviceStatus.sampling;` below 

https://github.com/cph-cachet/carp.sensing-flutter/blob/e7d8981a970e434eeac84b7e7bd1a8e7b52c1394/packages/carp_esense_package/lib/esense_device_manager.dart#L105-L128

**Comment by bardram** [comment]
The status `sampling` has been removed in version 0.40.0. It makes little sense to have this status, since a device is serving several "probes" (like both the eSense button and events probes), and it is hard to determine the semantics of when a device is sampling -- this is the probe which have this status (which is called `resumed`).

**Comment by bardram** [comment]
Released with version 0.40.0.
