### ISSUE TITLE
Studycontroller not initializing

### ISSUE THREAD

**Issue by attex** [cph-cachet/carp.sensing-flutter#93]
Hi there i am getting an when initializing the study controller.

Unhandled Exception: NoSuchMethodError: The getter 'type' was called on null.

`
_log() async {
   SamplingPackageRegistry.register(MovisensSamplingPackage());

    Study study = Study("1234", "bardram", name: "bardram study");
    study.addTriggerTask(
      ImmediateTrigger(), // a simple trigger that starts immediately
      Task()
        ..addMeasure(MovisensMeasure(MeasureType(NameSpace.CARP, MovisensSamplingPackage.MOVISENS),
            name: "movisens",
            enabled: true,
            address: '00:07:80:78:63:A5',
            deviceName: "MOVISENS Sensor 00840",
            height: 178,
            weight: 77,
            age: 32,
            gender: Gender.male,
            sensorLocation: SensorLocation.chest)));
   StudyController controller = StudyController(study);

  // await initialization before starting
  await controller.initialize();
  controller.resume();

  // listening on all data events from the study
  controller.events.forEach(print);
  }'

**Comment by bardram** [comment]
Hi @attex -- We've recently released new versions of all the CAMS packages, including the core `carp_mobile_sensing` and the Movisens sampling package. This bug seems to related to an old version, so please try to upgrade to the latest versions.

I've create a small test app with your configuration above, and it compiles fine. I can't test it though, since I don't have a Movisens device with me right now.
